const SeriesTypes = {
  // ACTION TYPES FOR SERIES AIRING TODAY
  GET_SERIES_AIRING_TODAY_START: "GET_SERIES_AIRING_TODAY_START",
  GET_SERIES_AIRING_TODAY_SUCCESS: "GET_SERIES_AIRING_TODAY_SUCCESS",
  GET_SERIES_AIRING_TODAY_FAILURE: "GET_SERIES_AIRING_TODAY_FAILURE",
  // ACTION TYPES FOR SERIES ON THE AIR
  GET_ON_THE_AIR_SERIES_START: "GET_ON_THE_AIR_SERIES_START",
  GET_ON_THE_AIR_SERIES_SUCCESS: "GET_ON_THE_AIR_SERIES_SUCCESS",
  GET_ON_THE_AIR_SERIES_FAILURE: "GET_ON_THE_AIR_SERIES_FAILURE",
  // ACTION TYPES FOR TOP RATED SERIES
  GET_TOP_RATED_SERIES_START: "GET_TOP_RATED_SERIES_START",
  GET_TOP_RATED_SERIES_SUCCESS: "GET_TOP_RATED_SERIES_SUCCESS",
  GET_TOP_RATED_SERIES_FAILURE: "GET_TOP_RATED_SERIES_FAILURE",
  // ACTIONS TYPES FOR TRENDING SERIES
  GET_TRENDING_SERIES_START: "GET_TRENDING_SERIES_START",
  GET_TRENDING_SERIES_SUCCESS: "GET_TRENDING_SERIES_SUCCESS",
  GET_TRENDING_SERIES_FAILURE: "GET_TRENDING_SERIES_FAILURE",
  // ACTIONS TYPES FOR POPULAR SERIES
  GET_POPULAR_SERIES_START: "GET_POPULAR_SERIES_START",
  GET_POPULAR_SERIES_SUCCESS: "GET_POPULAR_SERIES_SUCCESS",
  GET_POPULAR_SERIES_FAILURE: "GET_POPULAR_SERIES_FAILURE"
};

export default SeriesTypes;
