const SeriesTypes = {
  // ACTION TYPES FOR TV ON THE AIR
  GET_ON_AIR_SERIES_START: "GET_ON_AIR_SERIES_START",
  GET_ON_AIR_SERIES_SUCCESS: "GET_ON_AIR_SERIES_SUCCESS",
  GET_ON_AIR_SERIES_FAILURE: "GET_ON_AIR_SERIES_FAILURE",
  // ACTIONS TYPES FOR TRENDING SERIES
  GET_TRENDING_SERIES_START: "GET_TRENDING_SERIES_START",
  GET_TRENDING_SERIES_SUCCESS: "GET_TRENDING_SERIES_SUCCESS",
  GET_TRENDING_SERIES_FAILURE: "GET_TRENDING_SERIES_FAILURE"
};

export default SeriesTypes;
