const AppConfigTypes = {
  GET_IMAGE_CONFIG_START: "GET_IMAGE_CONFIG_START",
  GET_IMAGE_CONFIG_SUCCESS: "GET_IMAGE_CONFIG_SUCCESS",
  GET_IMAGE_CONFIG_FAILURE: "GET_IMAGE_CONFIG_FAILURE"
};

export default AppConfigTypes;
