const AppConfigTypes = {
  // ACTION TYPES FOR GETTING IMAGE CONFIGURATIONS
  GET_IMAGE_CONFIG_START: "GET_IMAGE_CONFIG_START",
  GET_IMAGE_CONFIG_SUCCESS: "GET_IMAGE_CONFIG_SUCCESS",
  GET_IMAGE_CONFIG_FAILURE: "GET_IMAGE_CONFIG_FAILURE",
  // PAGINATION
  SET_PAGINATION: "SET_PAGINATION"
};

export default AppConfigTypes;
