const MoviesTypes = {
  // ACTION TYPES FOR NOW PLAYING MOVIES
  GET_NOW_PLAYING_START: "GET_NOW_PLAYING_START",
  GET_NOW_PLAYING_SUCCESS: "GET_NOW_PLAYING_SUCCESS",
  GET_NOW_PLAYING_FAILURE: "GET_NOW_PLAYING_FAILURE"
};

export default MoviesTypes;
