const MoviesTypes = {
  // ACTION TYPES FOR NOW PLAYING MOVIES
  GET_NOW_PLAYING_START: "GET_NOW_PLAYING_START",
  GET_NOW_PLAYING_SUCCESS: "GET_NOW_PLAYING_SUCCESS",
  GET_NOW_PLAYING_FAILURE: "GET_NOW_PLAYING_FAILURE",
  // ACTIONS TYPES FOR TREANDING MOVIES
  GET_TRENDING_MOVIES_START: "GET_TRENDING_MOVIES_START",
  GET_TRENDING_MOVIES_SUCCESS: "GET_TRENDING_MOVIES_SUCCESS",
  GET_TRENDING_MOVIES_FAILURE: "GET_TRENDING_MOVIES_FAILURE"
};

export default MoviesTypes;
