const MoviesTypes = {
  // ACTION TYPE TO GET EITHER BELOW
  GET_MOVIES_START: "GET_MOVIES_START",
  // ACTION TYPES FOR NOW PLAYING MOVIES
  GET_NOW_PLAYING_START: "GET_NOW_PLAYING_START",
  GET_NOW_PLAYING_SUCCESS: "GET_NOW_PLAYING_SUCCESS",
  GET_NOW_PLAYING_FAILURE: "GET_NOW_PLAYING_FAILURE",
  // ACTIONS TYPES FOR TREANDING MOVIES
  GET_TRENDING_MOVIES_START: "GET_TRENDING_MOVIES_START",
  GET_TRENDING_MOVIES_SUCCESS: "GET_TRENDING_MOVIES_SUCCESS",
  GET_TRENDING_MOVIES_FAILURE: "GET_TRENDING_MOVIES_FAILURE",
  // ACTIONS TYPES FOR POPULAR MOVIES
  GET_POPULAR_MOVIES_START: "GET_POPULAR_MOVIES_START",
  GET_POPULAR_MOVIES_SUCCESS: "GET_POPULAR_MOVIES_SUCCESS",
  GET_POPULAR_MOVIES_FAILURE: "GET_POPULAR_MOVIES_FAILURE",
  // ACTION TYPES FOR TOP RATED MOVIES
  GET_TOP_RATED_MOVIES_START: "GET_TOP_RATED_MOVIES_START",
  GET_TOP_RATED_MOVIES_SUCCESS: "GET_TOP_RATED_MOVIES_SUCCESS",
  GET_TOP_RATED_MOVIES_FAILURE: "GET_TOP_RATED_MOVIES_FAILURE",
  // ACTION TYPES FOR UPCOMING MOVIES
  GET_UPCOMING_MOVIES_START: "GET_UPCOMING_MOVIES_START",
  GET_UPCOMING_MOVIES_SUCCESS: "GET_UPCOMING_MOVIES_SUCCESS",
  GET_UPCOMING_MOVIES_FAILURE: "GET_UPCOMING_MOVIES_FAILURE",
  // GET MOVIE DETAILS
  GET_MOVIE_DETAILS_START: "GET_MOVIE_DETAILS_START",
  GET_MOVIE_DETAILS_SUCCESS: "GET_MOVIE_DETAILS_SUCCESS",
  GET_MOVIE_DETAILS_FAILRUE: "GET_MOVIE_DETAILS_FAILURE",
  // GET MOVIE CAST AND CREW
  GET_MOVIE_CREDITS_SUCCESS: "GET_MOVIE_CREDITS_SUCCESS",
  GET_MOVIE_CREDITS_FAILURE: "GET_MOVIE_CREDITS_FAILURE",
  // GET SIMILAR MOVIES
  GET_SIMILAR_MOVIES_SUCCESS: "GET_SIMILAR_MOVIES_SUCCESS",
  GET_SIMILAR_MOVIES_FAILURE: "GET_SIMILAR_MOVIES_FAILURE"
};

export default MoviesTypes;
