const GenreTypes = {
  GET_LIST_OF_MOVIES_GENRES_START: "GET_LIST_OF_MOVIES_GENRES_START",
  GET_LIST_OF_MOVIES_GENRES_SUCCESS: "GET_LIST_OF_MOVIES_GENRES_SUCCESS",
  GET_LIST_OF_MOVIES_GENRES_FAILURE: "GET_LIST_OF_MOVIES_GENRES_FAILURE",
  GET_LIST_OF_SERIES_GENRES_START: "GET_LIST_OF_SERIES_GENRES_START",
  GET_LIST_OF_SERIES_GENRES_SUCCESS: "GET_LIST_OF_SERIES_GENRES_SUCCESS",
  GET_LIST_OF_SERIES_GENRES_FAILURE: "GET_LIST_OF_SERIES_GENRES_FAILURE"
};

export default GenreTypes;
