const GenreTypes = {
  GET_MOVIES_GENRES_START: "GET_MOVIES_GENRES_START",
  GET_MOVIES_GENRES_SUCCESS: "GET_MOVIES_GENRES_SUCCESS",
  GET_MOVIES_GENRES_FAILURE: "GET_MOVIES_GENRES_FAILURE",
  GET_SERIES_GENRES_START: "GET_SERIES_GENRES_START",
  GET_SERIES_GENRES_SUCCESS: "GET_SERIES_GENRES_SUCCESS",
  GET_SERIES_GENRES_FAILURE: "GET_SERIES_GENRES_FAILURE"
};

export default GenreTypes;
