const PersonTypes = {
  FETCH_PERSON_DETAILS_START: "FETCH_PERSON_DETAILS_START",
  FETCH_PERSON_DETAILS_SUCCESS: "FETCH_PERSON_DETAILS_SUCCESS",
  FETCH_PERSON_DETAILS_FAILURE: "FETCH_PERSON_DETAILS_FAILURE",
  TOGGLE_MODAL_WINDOW: "TOGGLE_MODAL_WINDOW"
};

export default PersonTypes;
